services:
  express-app:
    image: pedrojosealmeid/express-app:latest
    ports:
      - 8080:8080
    container_name: express-app-cicd-exercise
    restart: unless-stopped
  
  watchtower:
    image: containrrr/watchtower:1.7.1
    environment:
      -  WATCHTOWER_POLL_INTERVAL=30 # Poll every 30 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: express-app-cicd-exercise